# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-4752b97e-2401-4612-ae8c-01b7ea70ac3e";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-4752b97e-2401-4612-ae8c-01b7ea70ac3e".device = "/dev/disk/by-uuid/4752b97e-2401-4612-ae8c-01b7ea70ac3e";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/ACA1-B19A";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-f7c388a2-4a30-4933-90d4-bb703b0c8fa2"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
